name: Deploy Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # 必要なパッケージをインストール（html-minifier-terserなど）
      - name: Install dependencies
        run: |
          npm install html-minifier-terser

      # HTMLファイルの圧縮
      - name: Minify HTML files
        run: |
          npx html-minifier-terser ./src/*.html --output ./dist/

      # `publish`ブランチにデプロイ
      - name: Deploy to publish branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b publish
          git add .
          git commit -m "Deploy to publish branch"
          git push --force origin publish
