name: Deploy Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # 必要なパッケージをインストール（html-minifier-terser、clean-css-cliなど）
      - name: Install dependencies
        run: |
          npm install html-minifier-terser

      # HTMLファイルの圧縮
      - name: Minify HTML files
        run: |
          mkdir -p ./publish  # 出力先ディレクトリを作成
            for file in ./src/*.html; do
            npx html-minifier-terser "$file" --output "./publish/$(basename $file)" --collapse-whitespace --remove-comments --minify-css --minify-js
          done

      # 画像ファイルのコピー
      - name: Copy image files
        run: |
          mkdir -p ./publish/image
          cp -r ./image/* ./publish/image/

      # `publish`ブランチにデプロイ
      - name: Deploy to publish branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b publish
          git add ./publish
          git commit -m "Deploy to publish branch"
          git pull origin publish --allow-unrelated-histories --rebase --autostash
          git push origin `git subtree split --prefix publish publish`:publish --force
